# Generated by Django 2.1.2 on 2018-10-17 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mischismes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chismes',
            new_name='Chisme',
        ),
    ]
